update travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,27 +1,135 @@
-language: php
+#
+# Travis Setup
+#
 
-php:
-  - 7.1
-  - 7.2
-  - 7.3
-
-# run build against hhvm but allow them to fail
-# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
-matrix:
-  fast_finish: true
+# use ubuntu trusty for newer version of nodejs, used for JS testing
+dist: trusty
 
 # faster builds on new travis setup not using sudo
-sudo: false
+# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
+#sudo: false
+sudo: required
+group: edge
+
+# build only on master branches
+# commented as this prevents people from running builds on their forks:
+# https://github.com/yiisoft/yii2/commit/bd87be990fa238c6d5e326d0a171f38d02dc253a
+#branches:
+#  only:
+#    - master
+#    - 3.0
+
+
+#
+# Test Matrix
+#
+
+language: php
+
+env:
+  global:
+    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
+    - TASK_TESTS_PHP=1
+    - TASK_TESTS_COVERAGE=0
+    - TRAVIS_SECOND_USER=travis_two
+
+
+services:
+  - mysql
 
 # cache vendor dirs
 cache:
   directories:
+    - vendor
     - $HOME/.composer/cache
+    - $HOME/.npm
+
+# try running against postgres 9.6
+addons:
+  postgresql: "9.6"
+  apt:
+    sources:
+      - mysql-5.7-trusty
+    packages:
+      - mysql-server
+  code_climate:
+    repo_token: 2935307212620b0e2228ab67eadd92c9f5501ddb60549d0d86007a354d56915b
+
+matrix:
+  fast_finish: true
+  include:
+    - php: 7.3
+    - php: 7.2
+
+    # run tests coverage on PHP 7.1
+    - php: 7.1
+      env: TASK_TESTS_COVERAGE=1
+    - php: nightly
+      services:
+        - mysql
+
+  allow_failures:
+    - php: nightly
 
 install:
-  - travis_retry composer self-update && composer --version
+  - |
+    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
+      # disable xdebug for performance reasons when code coverage is not needed
+      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
+    fi
+
+  # install composer dependencies
+  - travis_retry composer self-update
   - export PATH="$HOME/.composer/vendor/bin:$PATH"
-  - travis_retry composer install --prefer-dist --no-interaction
+  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
+
+before_script:
+  # show some versions and env information
+  - php --version
+  - composer --version
+  - |
+    if [ $TASK_TESTS_PHP == 1 ]; then
+      php -r "echo INTL_ICU_VERSION . \"\n\";"
+      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
+      mysql --version
+    fi
+
+  # initialize databases
+  - |
+    if [ $TASK_TESTS_PHP == 1 ]; then
+      mysql_upgrade
+      travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
+      mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
+      mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
+      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
+    fi
+
+  # enable code coverage
+  - |
+    if [ $TASK_TESTS_COVERAGE == 1 ]; then
+      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
+    fi
+
+  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
+  # For Yii2 tests, messages will be enabled by tests/bootstrap.php
+  - |
+    if [[ $TRAVIS_PHP_VERSION == 7.2 || $TRAVIS_PHP_VERSION = nightly ]]; then
+      echo 'Disabled DEPRECATED notifications for PHP >= 7.2';
+      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
+      phpenv config-add /tmp/php-config.ini;
+    fi
+
 
 script:
-  - vendor/bin/phpunit $PHPUNIT_FLAGS
+  # PHP tests
+  - |
+    if [ $TASK_TESTS_PHP == 1 ]; then
+      vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group wincache,xcache
+    fi
+
+after_script:
+  - |
+    if [ $TASK_TESTS_COVERAGE == 1 ]; then
+      travis_retry wget https://scrutinizer-ci.com/ocular.phar
+      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
+    fi
